spring:
  datasource:
    url: jdbc:h2:mem:hiringdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: info
    org.springframework.web.client.RestTemplate: info
    com.example.hiring: info

app:
  hiring:
    base-url: https://bfhldevapigw.healthrx.co.in/hiring
    generate-webhook-path: /generateWebhook/JAVA
    test-webhook-path: /testWebhook/JAVA
  applicant:
    name: "John Doe"
    regNo: "REG12347"
    email: "john@example.com"
  sql:
    # Optionally set inline SQL (otherwise files under classpath:sql/ are used)
    # question1: ""
    # question2: ""
